### ISSUE TITLE
Nested factory may be called twice.

### ISSUE THREAD

**Issue by rapthead** [skovy/cooky-cutter#15]
Child factory will be called twice if child factory passed in override and parent factory has derivation that is depend on child factory field.
```javascript
import { define, derive } from 'cooky-cutter'

interface IChild {
    id: number
}

interface IParent {
    child_id: number | null
    child?: IChild
}

const child = define<IChild>({
    id: (i: number) => i
})

const parent = define<IParent>({
    child_id: derive<IParent, number | null>(
        ({ child }) => child ? child.id : null,
        'child',
    ),
})

console.log(parent({
    child
}))
```

It outputs `{ child: { id: 2 }, child_id: 1 }`

Epected behaviour is `{ child: { id: 1 }, child_id: 1 }`

**Comment by skovy** [comment]
Thanks for the report @rapthead! Can you try [`1.3.1`](https://www.npmjs.com/package/cooky-cutter)? It should now be resolved. Appreciate the test case as well!
