### ISSUE TITLE
Is it possible to reset the sequence between tests?

### ISSUE THREAD

**Issue by aaronmcadam** [skovy/cooky-cutter#23]
My tests depend on the sequence resetting, as you can see here in this codesandbox: https://codesandbox.io/s/nifty-dew-kx0bj

Do I need to configure jest somehow, or is this just not as supported use case for `sequence`?

**Comment by aaronmcadam** [comment]
https://github.com/willryan/factory.ts#basic-factory has the a method on factories called `resetSequenceNumber()`, maybe we could have that?

**Comment by skovy** [comment]
@aaronmcadam can you give https://www.npmjs.com/package/cooky-cutter/v/1.4.0 a try?

**Comment by aaronmcadam** [comment]
@skovy This works well, thanks!
