### ISSUE TITLE
Work with immutable (readonly) types

### ISSUE THREAD

**Issue by scttdavs** [skovy/cooky-cutter#28]
We're using a codegen tool with graphql and it's best practice to generate immutable types (that are all readonly). Using arrays with cooky-cutter does not work with that and we get type errors. Turning off the immutable option and regenerating the type does make it work though.

It would be nice to support both regular and readonly arrays.

```ts
type Foo {
    readonly bars: ReadOnlyArray<Bar>
}
```
```ts
const fooFactory = define<Foo>({
    bars: array(barFactory, 2)
})
```
that results in 
```
Type 'ArrayFactory<Bar>' is not assignable to type 'readonly Bar[] | ArrayFactory<never> | AttributeFunction<readonly Bar[]> | Factory<readonly Bar[]> | DerivedFunction<Foo, readonly Bar[]>'.
  Type 'ArrayFactory<Bar>' is not assignable to type 'ArrayFactory<never>'.
    Type 'Bar' is not assignable to type 'never'.ts(2322)
```

**Comment by skovy** [comment]
Hey @scttdavs, thanks for the information.

Looks like the example is partial, but I was able to create a failing test case (with type errors) in the linked pull request. Are there any other cases outside of `ReadonlyArray` that you had issues?

If not, can you try: https://www.npmjs.com/package/cooky-cutter/v/1.5.3?

If you still have issues, can you create a Codesandbox or open a pull request with failing test cases (doesn't need to fix them).
