### ISSUE TITLE
How to reset index in attribute functions?

### ISSUE THREAD

**Issue by screendriver** [skovy/cooky-cutter#42]
Is it possible to reset the index in attribute functions? Right now I want to write following test:

```ts
import { parseISO, subYears, formatISO } from 'date-fns';
import { define, array } from 'cooky-cutter';

const person = define<Person>({
  birthDate: '1980-10-01T15:12:52.710Z';
});

test('filters persons that are older than 30 years', () => {
  const startDate = '2020-10-01T15:12:52.710Z';
  const personsFactory = array(person, 35);
  const persons = personsFactory({
    birthDate: (index: number) => formatISO(subYears(startDate, index)),
  });
  const filtered = filterPersonsOlderThan(persons, 30)
  assert.equal(filtered.length, 5)
});

test('returns an empty Array when all persons are younger than 30 years', () => {
  const startDate = '2020-10-01T15:12:52.710Z';
  const personsFactory = array(person, 15);
  const persons = personsFactory({
    birthDate: (index: number) => formatISO(subYears(startDate, index)),
  });
  const filtered = filterPersonsOlderThan(persons, 30)
  assert.equal(filtered.length, 0)
});
```

The main problem here why the second test will fail is because `index` is not starting at `1` in the second test. It will continue with `36` which is fine most of the time but not in this case.

One workaround would be to define `person` within every test separately. But this is not a good solution when you orchestrate many objects with `cooky-cutter` together. A second workaround would be to rely on the incremented `index` from the previous test but then the tests are not isolated anymore and share state.

**Comment by skovy** [comment]
Hi @screendriver, yes it is possible: https://skovy.github.io/cooky-cutter/#/api?id=factory-function

> The internal sequence can be reset by calling `resetSequence()` on the factory returned from define or extend.

**Comment by screendriver** [comment]
Ah, thanks! 🤝 For the record: in my example you can reset the index with following code:

```ts
test('filters persons that are older than 30 years', () => {
  const startDate = '2020-10-01T15:12:52.710Z';
  person.resetSequence(); // ####### Here ist the reset #######
  const personsFactory = array(person, 35);
  const persons = personsFactory({
    birthDate: (index: number) => formatISO(subYears(startDate, index)),
  });
  const filtered = filterPersonsOlderThan(persons, 30)
  assert.equal(filtered.length, 5)
});
```
