### ISSUE TITLE
Using cooky-cutter with faker library

### ISSUE THREAD

**Issue by piyushchauhan2011** [skovy/cooky-cutter#50]
I was wondering if we can use the library with faker.js to generate random data while defining factories @skovy

**Comment by skovy** [comment]
@piyushchauhan2011 you should be able to use any function for a key in the factory. Building on the README example, it should be possible to drop in any faker logic or library. For example:

```ts
import faker from "...";

const user = define<User>({
  id: () => faker.id(),
  firstName: () => faker.firstrName(),
  lastName: () => faker.lastName(),
  age: () => faker.randomNumber()
});
```

**Comment by piyushchauhan2011** [comment]
Awesome, thanks! 🚀
